// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TT.EMS.Infrastructure.Persistence;

#nullable disable

namespace TT.EMS.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240905130651_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TT.EMS.Domain.Employee.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d88d221-75a3-416a-8556-336c1e9746a7"),
                            Age = 25,
                            FirstName = "John",
                            LastName = "Doe",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = new Guid("115bf8ee-142c-42ce-8fc9-83bc47c1ae6c"),
                            Age = 27,
                            FirstName = "Jane",
                            LastName = "Doe",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = new Guid("cf8bc349-2e20-4a1b-ac63-4722dff73502"),
                            Age = 53,
                            FirstName = "Alice",
                            LastName = "Doe",
                            Sex = "Female"
                        },
                        new
                        {
                            Id = new Guid("d6fad965-d98f-4bf5-878c-7644b0b139d4"),
                            Age = 59,
                            FirstName = "Bob",
                            LastName = "Doe",
                            Sex = "Male"
                        },
                        new
                        {
                            Id = new Guid("30f4105d-fe87-43cf-a4fa-d6d15541c9ff"),
                            Age = 20,
                            FirstName = "Charlie",
                            LastName = "Dupa",
                            Sex = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
